"""empty message

Revision ID: 1564025d7d3b
Revises: 64f3b55ea484
Create Date: 2026-06-14 21:41:42.640109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1564025d7d3b'
down_revision: Union[str, Sequence[str], None] = '64f3b55ea484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('estimated_tokens', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('action_definitions', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('action_definitions', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('action_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trigger_definitions', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column(
    'trigger_definitions',
    'aliases',
    existing_type=postgresql.ARRAY(sa.TEXT()),
    type_=postgresql.JSONB(astext_type=sa.Text()),
    nullable=False,
    postgresql_using="to_jsonb(aliases)"
        )

    op.alter_column(
        'action_definitions',
        'aliases',
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        postgresql_using="to_jsonb(aliases)"
    )
    op.alter_column('trigger_definitions', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('trigger_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trigger_definitions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trigger_definitions', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('trigger_definitions', 'aliases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('trigger_definitions', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('action_definitions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_definitions', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('action_definitions', 'aliases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('action_definitions', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('generation_logs')
    # ### end Alembic commands ###
