"""redesign action execution models

Revision ID: 17a145e47f42
Revises: c9f1a2b3d4e5
Create Date: 2026-07-26 21:52:20.396065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17a145e47f42'
down_revision: Union[str, Sequence[str], None] = 'c9f1a2b3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_definitions', sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('action_definitions', sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('action_definitions', sa.Column('execution_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('action_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('action_definitions', 'handler_name')
    op.drop_column('action_definitions', 'config_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_definitions', sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('action_definitions', sa.Column('handler_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('action_definitions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_definitions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('action_definitions', 'execution_template')
    op.drop_column('action_definitions', 'output_schema')
    op.drop_column('action_definitions', 'input_schema')
    # ### end Alembic commands ###
