"""add trace columns

Revision ID: 23a7ad18f738
Revises: 8956a5decb4b
Create Date: 2026-05-30 23:11:47.026574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23a7ad18f738'
down_revision: Union[str, Sequence[str], None] = '8956a5decb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('span_id', sa.String(length=100), nullable=True),
    sa.Column('parent_span_id', sa.String(length=100), nullable=True),
    sa.Column('workflow_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('execution_step_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_step_id'], ['execution_steps.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_events_created_at'), 'trace_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_trace_events_event_type'), 'trace_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_trace_events_execution_step_id'), 'trace_events', ['execution_step_id'], unique=False)
    op.create_index(op.f('ix_trace_events_id'), 'trace_events', ['id'], unique=False)
    op.create_index(op.f('ix_trace_events_span_id'), 'trace_events', ['span_id'], unique=False)
    op.create_index(op.f('ix_trace_events_trace_id'), 'trace_events', ['trace_id'], unique=False)
    op.create_index(op.f('ix_trace_events_workflow_execution_id'), 'trace_events', ['workflow_execution_id'], unique=False)
    op.add_column('execution_steps', sa.Column('span_id', sa.String(length=100), nullable=True))
    op.add_column('execution_steps', sa.Column('parent_span_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_execution_steps_span_id'), 'execution_steps', ['span_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_steps_span_id'), table_name='execution_steps')
    op.drop_column('execution_steps', 'parent_span_id')
    op.drop_column('execution_steps', 'span_id')
    op.drop_index(op.f('ix_trace_events_workflow_execution_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_trace_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_span_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_execution_step_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_event_type'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_created_at'), table_name='trace_events')
    op.drop_table('trace_events')
    # ### end Alembic commands ###
