"""baseline_clean_schema

Revision ID: 372acdc21acf
Revises: 
Create Date: 2026-09-06 00:28:26.520433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '372acdc21acf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_type', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('generation_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('estimated_tokens', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_type', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('evaluation_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brd_action', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_action_definition_id', sa.Integer(), nullable=True),
    sa.Column('expected_action_name', sa.String(), nullable=True),
    sa.Column('source_brd', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expected_action_definition_id'], ['action_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('raw_input', sa.String(), nullable=False),
    sa.Column('parsed_rule_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('skill_file_id', sa.String(length=255), nullable=True),
    sa.Column('skill_file_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_domain'), 'workflows', ['domain'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index(op.f('ix_workflows_workspace_id'), 'workflows', ['workspace_id'], unique=False)
    op.create_table('workspace_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('authentication_type', sa.String(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workflow_id'), 'audit_logs', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('business_rule_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_workspace_id', sa.Integer(), nullable=False),
    sa.Column('source_workflow_knowledge_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('op', sa.String(length=20), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('allowed_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scope_workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_workflow_knowledge_id'], ['workflow_knowledge.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rule_definitions_scope_workspace_id'), 'business_rule_definitions', ['scope_workspace_id'], unique=False)
    op.create_table('workflow_action_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('extract_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('matched_action_definition_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'MAPPED', 'UNMAPPED', 'FAILED', name='mappingstatus'), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('top_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('action_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('catalog_description', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_type', sa.String(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('responsible_actors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['matched_action_definition_id'], ['action_definitions.id'], ),
    sa.ForeignKeyConstraint(['workflow_knowledge_id'], ['workflow_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_knowledge_id'], ['workflow_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_business_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_knowledge_id'], ['workflow_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('source_workflow_id', sa.Integer(), nullable=False),
    sa.Column('source_step_id', sa.String(), nullable=False),
    sa.Column('source_action', sa.String(), nullable=False),
    sa.Column('target_workflow_id', sa.Integer(), nullable=False),
    sa.Column('target_trigger', sa.String(), nullable=False),
    sa.Column('match_type', sa.Enum('name_match', 'fts_match', 'rule_mention', name='chainmatchtype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('suggested', 'accepted', 'rejected', 'auto', name='chainstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_workflow_id'], ['workflows.id'], ),
    sa.ForeignKeyConstraint(['target_workflow_id'], ['workflows.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_chains_source_workflow_id'), 'workflow_chains', ['source_workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_chains_target_workflow_id'), 'workflow_chains', ['target_workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_chains_workspace_id'), 'workflow_chains', ['workspace_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_entity_id'), 'workflow_runs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_event_type'), 'workflow_runs', ['event_type'], unique=False)
    op.create_index(op.f('ix_workflow_runs_id'), 'workflow_runs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('workflow_trigger_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('extracted_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('matched_trigger_definition_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'MAPPED', 'UNMAPPED', 'FAILED', name='mappingstatus'), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('trigger_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('catalog_description', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_type', sa.String(), nullable=True),
    sa.Column('applicable_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('responsible_actors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['matched_trigger_definition_id'], ['trigger_definitions.id'], ),
    sa.ForeignKeyConstraint(['workflow_knowledge_id'], ['workflow_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('source_rule_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_rule_id'], ['business_rule_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_role_assignment_user_workspace')
    )
    op.create_index(op.f('ix_role_assignments_role'), 'role_assignments', ['role'], unique=False)
    op.create_index(op.f('ix_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_workspace_id'), 'role_assignments', ['workspace_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_run_id', sa.BigInteger(), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_correlation_id'), 'workflow_executions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_id'), 'workflow_executions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_trace_id'), 'workflow_executions', ['trace_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_run_id'), 'workflow_executions', ['workflow_run_id'], unique=False)
    op.create_table('execution_steps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('span_id', sa.String(length=100), nullable=True),
    sa.Column('parent_span_id', sa.String(length=100), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_steps_id'), 'execution_steps', ['id'], unique=False)
    op.create_index(op.f('ix_execution_steps_span_id'), 'execution_steps', ['span_id'], unique=False)
    op.create_index(op.f('ix_execution_steps_status'), 'execution_steps', ['status'], unique=False)
    op.create_index(op.f('ix_execution_steps_workflow_execution_id'), 'execution_steps', ['workflow_execution_id'], unique=False)
    op.create_table('human_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('step_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=True),
    sa.Column('on_timeout', sa.String(length=10), nullable=True),
    sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_execution_id'], ['execution_steps.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_tasks_id'), 'human_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_human_tasks_status'), 'human_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_human_tasks_step_execution_id'), 'human_tasks', ['step_execution_id'], unique=False)
    op.create_index(op.f('ix_human_tasks_timeout_at'), 'human_tasks', ['timeout_at'], unique=False)
    op.create_index(op.f('ix_human_tasks_workflow_execution_id'), 'human_tasks', ['workflow_execution_id'], unique=False)
    op.create_table('step_retry_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('step_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('status_at_attempt', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_execution_id'], ['execution_steps.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_retry_history_created_at'), 'step_retry_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_step_retry_history_id'), 'step_retry_history', ['id'], unique=False)
    op.create_index(op.f('ix_step_retry_history_step_execution_id'), 'step_retry_history', ['step_execution_id'], unique=False)
    op.create_index(op.f('ix_step_retry_history_trigger'), 'step_retry_history', ['trigger'], unique=False)
    op.create_index(op.f('ix_step_retry_history_workflow_execution_id'), 'step_retry_history', ['workflow_execution_id'], unique=False)
    op.create_table('trace_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('span_id', sa.String(length=100), nullable=True),
    sa.Column('parent_span_id', sa.String(length=100), nullable=True),
    sa.Column('workflow_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('execution_step_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_step_id'], ['execution_steps.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_events_created_at'), 'trace_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_trace_events_event_type'), 'trace_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_trace_events_execution_step_id'), 'trace_events', ['execution_step_id'], unique=False)
    op.create_index(op.f('ix_trace_events_id'), 'trace_events', ['id'], unique=False)
    op.create_index(op.f('ix_trace_events_span_id'), 'trace_events', ['span_id'], unique=False)
    op.create_index(op.f('ix_trace_events_trace_id'), 'trace_events', ['trace_id'], unique=False)
    op.create_index(op.f('ix_trace_events_workflow_execution_id'), 'trace_events', ['workflow_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_events_workflow_execution_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_trace_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_span_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_execution_step_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_event_type'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_created_at'), table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_index(op.f('ix_step_retry_history_workflow_execution_id'), table_name='step_retry_history')
    op.drop_index(op.f('ix_step_retry_history_trigger'), table_name='step_retry_history')
    op.drop_index(op.f('ix_step_retry_history_step_execution_id'), table_name='step_retry_history')
    op.drop_index(op.f('ix_step_retry_history_id'), table_name='step_retry_history')
    op.drop_index(op.f('ix_step_retry_history_created_at'), table_name='step_retry_history')
    op.drop_table('step_retry_history')
    op.drop_index(op.f('ix_human_tasks_workflow_execution_id'), table_name='human_tasks')
    op.drop_index(op.f('ix_human_tasks_timeout_at'), table_name='human_tasks')
    op.drop_index(op.f('ix_human_tasks_step_execution_id'), table_name='human_tasks')
    op.drop_index(op.f('ix_human_tasks_status'), table_name='human_tasks')
    op.drop_index(op.f('ix_human_tasks_id'), table_name='human_tasks')
    op.drop_table('human_tasks')
    op.drop_index(op.f('ix_execution_steps_workflow_execution_id'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_status'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_span_id'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_id'), table_name='execution_steps')
    op.drop_table('execution_steps')
    op.drop_index(op.f('ix_workflow_executions_workflow_run_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_trace_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_correlation_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_role_assignments_workspace_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_user_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_role'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_table('workflow_trigger_mapping')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_event_type'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_entity_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_workflow_chains_workspace_id'), table_name='workflow_chains')
    op.drop_index(op.f('ix_workflow_chains_target_workflow_id'), table_name='workflow_chains')
    op.drop_index(op.f('ix_workflow_chains_source_workflow_id'), table_name='workflow_chains')
    op.drop_table('workflow_chains')
    op.drop_table('workflow_business_rule')
    op.drop_table('workflow_actors')
    op.drop_table('workflow_action_mapping')
    op.drop_index(op.f('ix_business_rule_definitions_scope_workspace_id'), table_name='business_rule_definitions')
    op.drop_table('business_rule_definitions')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workflow_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('workspace_integrations')
    op.drop_index(op.f('ix_workflows_workspace_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_domain'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_table('workflow_knowledge')
    op.drop_table('evaluation_cases')
    op.drop_table('workspaces')
    op.drop_table('trigger_definitions')
    op.drop_table('generation_logs')
    op.drop_table('action_definitions')
    # ### end Alembic commands ###
