"""add embedding mapping fields

Revision ID: 6ebeab700faf
Revises: 94c78b53cc88
Create Date: 2026-07-05 16:34:44.235833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebeab700faf'
down_revision: Union[str, Sequence[str], None] = '94c78b53cc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_action_mapping', sa.Column('similarity_score', sa.Float(), nullable=True))
    op.add_column('workflow_trigger_mappings', sa.Column('similarity_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_trigger_mappings', 'similarity_score')
    op.drop_column('workflow_action_mapping', 'similarity_score')
    # ### end Alembic commands ###
