"""add trace fields

Revision ID: 8956a5decb4b
Revises: 93cb7d655ff7
Create Date: 2026-05-30 22:34:54.625711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8956a5decb4b'
down_revision: Union[str, Sequence[str], None] = '93cb7d655ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('trace_id', sa.String(length=100), nullable=True))
    op.add_column('workflow_executions', sa.Column('correlation_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_workflow_executions_correlation_id'), 'workflow_executions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_trace_id'), 'workflow_executions', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_trace_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_correlation_id'), table_name='workflow_executions')
    op.drop_column('workflow_executions', 'correlation_id')
    op.drop_column('workflow_executions', 'trace_id')
    # ### end Alembic commands ###
