"""add workflow run and execution changes

Revision ID: 93cb7d655ff7
Revises: fd7bafc2ad3b
Create Date: 2026-05-28 21:14:16.140783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cb7d655ff7'
down_revision: Union[str, Sequence[str], None] = 'fd7bafc2ad3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_retry_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_run_id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('retry_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('retry_strategy', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_retry_history')
    # ### end Alembic commands ###
