"""add workflow knowledge ingestion tables

Revision ID: 94c78b53cc88
Revises: b401fcc0ae11
Create Date: 2026-07-05 00:07:17.476462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c78b53cc88'
down_revision: Union[str, Sequence[str], None] = 'b401fcc0ae11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_action_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('extract_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('matched_action_definition_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matched_action_definition_id'], ['action_definitions.id'], ),
    sa.ForeignKeyConstraint(['workflow_knowledge_id'], ['workflow_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_knowledge_id'], ['workflow_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_business_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_knowledge_id'], ['workflow_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_external_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_knowledge_id'], ['workflow_knowledge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_trigger_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_knowledge_id', sa.Integer(), nullable=False),
    sa.Column('extracted_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('matched_trigger_definition_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matched_trigger_definition_id'], ['trigger_definitions.id'], ),
    sa.ForeignKeyConstraint(['workflow_knowledge_id'], ['workflow_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_trigger_mappings')
    op.drop_table('workflow_external_systems')
    op.drop_table('workflow_business_rule')
    op.drop_table('workflow_actors')
    op.drop_table('workflow_action_mapping')
    op.drop_table('workflow_knowledge')
    # ### end Alembic commands ###
