"""add vector embeddings

Revision ID: 9c3491d921ce
Revises: 95380ee900bc
Create Date: 2026-06-17 23:26:47.250672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector
# revision identifiers, used by Alembic.
revision: str = '9c3491d921ce'
down_revision: Union[str, Sequence[str], None] = '95380ee900bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('action_definitions', sa.Column('embedding', Vector(dim=384), nullable=True))
    op.add_column('trigger_definitions', sa.Column('embedding', Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trigger_definitions', 'embedding')
    op.drop_column('action_definitions', 'embedding')
    op.create_table('workflow_retry_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('workflow_run_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('workflow_execution_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('retry_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('error_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_strategy', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], name='workflow_retry_history_workflow_execution_id_fkey'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name='workflow_retry_history_workflow_run_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workflow_retry_history_pkey')
    )
    # ### end Alembic commands ###
