"""handler_added

Revision ID: b401fcc0ae11
Revises: 797a796b21e6
Create Date: 2026-06-21 21:01:58.572420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b401fcc0ae11'
down_revision: Union[str, Sequence[str], None] = '797a796b21e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_definitions', sa.Column('handler_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_definitions', 'handler_name')
    # ### end Alembic commands ###
