"""workspace workflow_integration models

Revision ID: fd12c88c1c06
Revises: 17a145e47f42
Create Date: 2026-07-26 22:03:28.978253

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fd12c88c1c06"
down_revision: Union[str, Sequence[str], None] = "17a145e47f42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("organization_name", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "workspace_integrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("integration_type", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=True),
        sa.Column(
            "authentication", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "credentials", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "action_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_knowledge_id", sa.Integer(), nullable=False),
        sa.Column("action_definition_id", sa.Integer(), nullable=False),
        sa.Column("workspace_integration_id", sa.Integer(), nullable=True),
        sa.Column("execution_type", sa.String(), nullable=False),
        sa.Column(
            "configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["action_definition_id"],
            ["action_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_knowledge_id"],
            ["workflow_knowledge.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_integration_id"],
            ["workspace_integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        
          # op.add_column('workflow_knowledge', sa.Column('workspace_id', sa.Integer(), nullable=False))
            # op.create_foreign_key(None, 'workflow_knowledge', 'workspaces', ['workspace_id'], ['id'])
            # # ### end Alembic commands ###
            # Step 1 - Add nullable column
        op.add_column(
                "workflow_knowledge",
                sa.Column("workspace_id", sa.Integer(), nullable=True),
            ),
        
            # Step 2 - Create a default workspace
        op.execute("""
            INSERT INTO workspaces
            (name, display_name, organization_name, active)
            VALUES
            (
                'default',
                'Default Workspace',
                'MFlows',
                TRUE
            )
            """),
        
            # Step 3 - Assign every existing workflow to it
        op.execute("""
            UPDATE workflow_knowledge
            SET workspace_id = (
                SELECT id
                FROM workspaces
                WHERE name = 'default'
            )
            """),
        
            # Step 4 - Make it mandatory
        op.alter_column(
                "workflow_knowledge",
                "workspace_id",
                nullable=False,
            ),
        
            # Step 5 - Add FK
        op.create_foreign_key(
                "fk_workflow_workspace",
                "workflow_knowledge",
                "workspaces",
                ["workspace_id"],
                ["id"],
            )
        
    )
  


    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workflow_knowledge", type_="foreignkey")
    op.drop_column("workflow_knowledge", "workspace_id")
    op.drop_table("action_configurations")
    op.drop_table("workspace_integrations")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
