WORKFLOW_STATUS_PENDING = "PENDING"
WORKFLOW_STATUS_RUNNING = "RUNNING"
WORKFLOW_STATUS_COMPLETED = "COMPLETED"
WORKFLOW_STATUS_FAILED = "FAILED"
WORKFLOW_STATUS_PAUSED = "PAUSED"
WORKFLOW_STATUS_WAITING_APPROVAL = "WAITING_APPROVAL"


STEP_STATUS_PENDING = "PENDING"
STEP_STATUS_RUNNING = "RUNNING"
STEP_STATUS_COMPLETED = "COMPLETED"
STEP_STATUS_FAILED = "FAILED"
STEP_STATUS_SKIPPED = "SKIPPED"
STEP_STATUS_WAITING = "WAITING"
STEP_STATUS_BLOCKED = "BLOCKED"


FINAL_WORKFLOW_STATES = {
    WORKFLOW_STATUS_COMPLETED,
    WORKFLOW_STATUS_FAILED,
}


FINAL_STEP_STATES = {
    STEP_STATUS_COMPLETED,
    STEP_STATUS_FAILED,
    STEP_STATUS_SKIPPED,
}
