"""
Trigger and action pattern registries for rule-based intent extraction.

Maps natural language surface forms to canonical trigger/action identifiers.
No database, no LLM, no embeddings — pure dictionary lookup.
"""

# Maps NL phrases to canonical trigger identifiers.
# Keys are lowercase surface forms found in natural language sentences.
TRIGGER_PATTERNS: dict[str, str] = {
    "payment is due":       "payment_due",
    "payment due":          "payment_due",
    "payment is missed":    "payment_missed",
    "payment missed":       "payment_missed",
    "loan is requested":    "loan_requested",
    "loan requested":       "loan_requested",
    "delivery failed":      "delivery_failed",
    "delivery is failed":   "delivery_failed",
    "account is locked":    "account_locked",
    "account locked":       "account_locked",
    "fraud is detected":    "fraud_detected",
    "fraud detected":       "fraud_detected",
    "ticket created":       "ticket_created",
    "ticket is created":    "ticket_created",
    "ticket unresolved":    "ticket_unresolved",
    "ticket is unresolved": "ticket_unresolved",
    "ticket escalated":     "ticket_unresolved",
    "sla breached":         "sla_breached",
    "sla is breached":      "sla_breached",
    "complaint created":    "complaint_created",
    "complaint is created": "complaint_created",
    "complaint escalated":  "complaint_escalated",
    "customer churned":     "customer_churned",
    "refund requested":     "refund_requested",
    "refund is requested":  "refund_requested",
    "survey completed":     "survey_completed",
    "patient admitted":     "patient_admitted",
    "patient is admitted":  "patient_admitted",
    "patient discharged":   "patient_discharged",
    "lab result ready":     "lab_result_ready",
    "appointment missed":   "appointment_missed",
    "medication overdue":   "medication_overdue",
    "critical vitals":      "critical_vitals",
    "insurance approved":   "insurance_approved",
    "insurance denied":     "insurance_denied",
    "followup due":         "followup_due",
    "follow up due":        "followup_due",
    "loan overdue":         "payment_missed",
    "customer reply":       "ticket_created",
}

# Maps NL phrases to canonical action identifiers.
ACTION_PATTERNS: dict[str, str] = {
    "send reminder":              "send_reminder",
    "send a reminder":            "send_reminder",
    "escalate case":              "escalate_case",
    "escalate the case":          "escalate_case",
    "assign senior officer":      "assign_senior_officer",
    "close case":                 "close_case",
    "close the case":             "close_case",
    "reject loan":                "reject_loan",
    "notify manager":             "notify_manager",
    "notify the manager":         "notify_manager",
    "validate payment":           "validate_payment",
    "send email notification":    "send_email_notification",
    "send email":                 "send_email_notification",
    "send sms notification":      "send_sms_notification",
    "send sms":                   "send_sms_notification",
    "send push notification":     "send_push_notification",
    "create audit record":        "create_audit_record",
    "trigger webhook":            "trigger_webhook",
    "update entity status":       "update_entity_status",
    "flag for review":            "flag_for_review",
    "lock account":               "lock_account",
    "unlock account":             "unlock_account",
    "generate report":            "generate_report",
    "create support ticket":      "create_support_ticket",
    "assign support agent":       "assign_support_agent",
    "escalate to tier2":          "escalate_to_tier2",
    "escalate to tier 2":         "escalate_to_tier2",
    "send sla breach alert":      "send_sla_breach_alert",
    "send sla alert":             "send_sla_breach_alert",
    "send customer update":       "send_customer_update",
    "resolve ticket":             "resolve_ticket",
    "send satisfaction survey":   "send_satisfaction_survey",
    "process refund":             "process_refund",
    "flag repeat complaint":      "flag_repeat_complaint",
    "close ticket no response":   "close_ticket_no_response",
    "schedule appointment":       "schedule_appointment",
    "send medication reminder":   "send_medication_reminder",
    "alert care team":            "alert_care_team",
    "escalate to specialist":     "escalate_to_specialist",
    "notify lab result":          "notify_lab_result",
    "trigger emergency protocol": "trigger_emergency_protocol",
    "send discharge instructions":"send_discharge_instructions",
    "flag high risk patient":     "flag_high_risk_patient",
    "request insurance approval": "request_insurance_approval",
    "send wellness check":        "send_wellness_check",
}
