EVENT_RECEIVED = "RECEIVED"
EVENT_PROCESSING = "PROCESSING"
EVENT_COMPLETED = "COMPLETED"
EVENT_FAILED = "FAILED"
EVENT_RETRY_SCHEDULED = "RETRY_SCHEDULED"
EVENT_DLQ = "DLQ"

# Step statuses — must match runtime/constants.py
STEP_PENDING = "PENDING"
STEP_RUNNING = "RUNNING"
STEP_COMPLETED = "COMPLETED"   # was STEP_SUCCESS = "SUCCESS" — fixed
STEP_FAILED = "FAILED"

REDIS_EVENT_QUEUE = "workflow_events"
REDIS_RETRY_QUEUE = "workflow_retry"
REDIS_DLQ = "workflow_dlq"
