"""
app/execution/python/action_handler_registry.py

ActionHandlerRegistry — maps handler name strings to Python callables.

This is the sole consumer of the action handler implementations.
Only PythonExecutor reads this registry.

Rule for inclusion:
  A handler belongs here if its execution is internal Python logic —
  state transitions, financial calculations, compliance checks, fraud
  screening, internal record creation, or database state changes.

  Communication/delivery actions (email, SMS, webhook) do NOT belong here.
  Those are handled by HttpExecutor using WorkspaceIntegration credentials.

  Document generation (PDF/CSV/Excel) DOES belong here: it is internal Python
  logic that produces a file and persists it via the file storage layer,
  returning a storage reference in the ActionResult.

CHAOS_MODE:
  If CHAOS_MODE=true, ACTION_HANDLER_MAP is replaced with its chaos-wrapped
  variant, which injects failure modes for testing retry/DLQ behaviour.
"""

import os

from app.execution.actions import (
    update_entity_status,
    flag_for_review,
    lock_account,
    unlock_account,
    close_case,
    escalate_case,
    assign_senior_officer,
    escalate_to_rm,
    create_audit_record,
    fail_randomly,
    validate_payment_handler,
    assess_creditworthiness,
    approve_loan,
    reject_loan,
    reject_loan_application,
    approve_underwriting,
    reject_underwriting,
    calculate_emi,
    calculate_risk_score,
    flag_high_risk_customer,
    disburse_loan,
    generate_loan_agreement,
    apply_credit,
    calculate_tax,
    create_payment,
    validate_transaction,
    verify_compliance,
    initiate_collection,
    assign_recovery_agent,
    initiate_legal_action,
    write_off_loan,
    restructure_loan,
    waive_penalty,
    open_account,
    close_account,
    upgrade_account,
    block_debit_card,
    issue_new_card,
    update_credit_limit,
    activate_overdraft,
    reactivate_dormant_account,
    hold_funds,
    release_funds,
    freeze_suspicious_account,
    reverse_transaction,
    charge_penalty,
    apply_interest,
    process_neft,
    process_rtgs,
    process_imps,
    aml_screening,
    sanctions_check,
    submit_regulatory_report,
    run_bureau_check,
    process_credit_check,
    reconcile_account,
    approve_invoice,
    initiate_kyc,
    complete_kyc,
    collect_documents,
    schedule_customer_callback,
)
from app.execution.domain_actions.support_actions import (
    create_support_ticket,
    assign_support_agent,
    escalate_to_tier2,
    flag_repeat_complaint,
    resolve_ticket,
    process_refund,
    close_ticket_no_response,
)
from app.execution.domain_actions.health_actions import (
    schedule_appointment,
    alert_care_team,
    escalate_to_specialist,
    trigger_emergency_protocol,
    flag_high_risk_patient,
    request_insurance_approval,
)
from app.execution.domain_actions.loan_actions import (
    run_cibil_check,
    run_income_verification,
    verify_submitted_documents,
    issue_sanction_letter,
    generate_repayment_schedule,
    link_insurance_to_loan,
    collect_post_disbursement_documents,
    generate_interest_certificate,
    update_cibil_post_closure,
)
from app.execution.domain_actions.home_loan_actions import (
    initiate_property_valuation,
    schedule_technical_visit,
    initiate_legal_verification,
    send_to_legal_team,
    raise_legal_query,
    legal_verification_cleared,
    register_mortgage,
    collect_original_property_documents,
    disburse_tranche,
    return_original_documents,
)
from app.execution.domain_actions.car_loan_actions import (
    initiate_vehicle_valuation,
    verify_dealer_invoice,
    coordinate_with_dealer,
    disburse_to_dealer,
    initiate_rc_hypothecation,
    verify_vehicle_insurance,
    release_hypothecation,
)
from app.execution.python.pdf.handler import generate_pdf
from app.execution.python.csv.handler import generate_csv
from app.execution.python.excel.handler import generate_excel
from app.execution.chaos_actions import (
    chaos_escalate_case,
    chaos_assign_senior_officer,
    chaos_reject_loan,
    chaos_close_case,
    _apply_chaos,
    _chaos_response,
)
from app.execution.domain_actions.catalog_stubs import (
    abort_workflow, activate_account_aggregator, activate_card,
    activate_pos_terminal, activate_sms_alerts, add_beneficiary,
    add_joint_holder, add_nominee, advise_letter_of_credit,
    allot_safe_deposit_locker, amend_letter_of_credit, apply_bounce_charges,
    apply_credit_card, apply_subvention, appraise_gold,
    approve_one_time_settlement, approve_restructuring, approve_top_up_loan,
    archive_document, assign_collection_agent, assign_collection_bucket,
    assign_credit_officer, assign_customer_segment, assign_field_officer,
    assign_legal_counsel, assign_relationship_manager, assign_telecalling_agents,
    auction_collateral, block_credit_card, block_fraudulent_transaction,
    block_upi_id, book_forex_deal, calculate_account_balance, calculate_alm_gap,
    calculate_credit_score, calculate_debt_service_ratio, calculate_eblr,
    calculate_eligibility, calculate_fd_interest, calculate_foreclosure_amount,
    calculate_forex_margin, calculate_group_utilization,
    calculate_hedge_effectiveness, calculate_interest, calculate_interest_rate,
    calculate_loan_eligibility, calculate_ltv_ratio, calculate_mark_to_market,
    calculate_mclr, calculate_penal_interest,
    calculate_penalty_on_premature_withdrawal, calculate_prepayment_charges,
    calculate_provision_coverage, calculate_rd_maturity, cancel_nach_mandate,
    cancel_scheduled_job, cancel_standing_instruction, capture_biometric,
    capture_customer_photograph, change_emi_date, charge_locker_rent,
    check_fema_compliance, check_pep_status, classify_asset_quality,
    classify_customer_risk, classify_npa, close_credit_card, close_deposit,
    close_fraud_case, close_transaction_investigation, collect_address_details,
    collect_address_proof, collect_asset_liability_details,
    collect_bank_account_details, collect_bank_statement, collect_biometrics,
    collect_business_details, collect_business_proof, collect_contact_details,
    collect_dependents_details, collect_digital_consent,
    collect_document_requirements, collect_education_details,
    collect_employment_certificate, collect_employment_details,
    collect_existing_loan_details, collect_family_details,
    collect_field_photographs, collect_field_verification, collect_geotag_data,
    collect_group_repayment, collect_guarantor_details, collect_identity_proof,
    collect_income_details, collect_income_proof, collect_insurance_certificate,
    collect_insurance_documents, collect_itr_documents, collect_legal_documents,
    collect_marital_status, collect_medical_history, collect_mortgage_documents,
    collect_next_of_kin_details, collect_nominee_details,
    collect_occupation_details, collect_personal_details, collect_photo,
    collect_property_details, collect_property_documents,
    collect_reference_details, collect_sanction_letter_copy,
    collect_selfie_verification, collect_signature, collect_signed_agreement,
    collect_tcs_on_remittance, collect_technical_documents,
    collect_vehicle_details, collect_vehicle_documents, collect_voice_biometric,
    collect_witness_details, compute_cost_of_funds, compute_depreciation,
    compute_drawing_power, compute_ecl, compute_gst,
    compute_interest_on_interest, compute_internal_rating, compute_nii,
    compute_provisioning, compute_recovery_progress, conditional_approve_loan,
    conduct_cgt, conduct_grt, conduct_personal_discussion, conduct_stock_audit,
    confirm_letter_of_credit, convert_to_card_emi, create_audit_event,
    create_collateral_charge, create_customer, create_customer_profile,
    create_fixed_deposit, create_group_loan, create_loan_application,
    create_mortgage_deed, create_notification_task, create_recurring_deposit,
    create_standing_instruction, credit_interest_to_account, ctr_reporting,
    deactivate_customer, deactivate_overdraft, deactivate_sms_alerts,
    deactivate_upi_mandate, deduct_tds, disable_international_usage,
    dispute_card_transaction, dissolve_group, downgrade_account,
    downgrade_account_rating, drill_locker, enable_international_usage,
    enable_internet_banking, enable_mobile_banking, enable_upi,
    enable_upi_autopay, enroll_health_insurance, enroll_life_insurance,
    enroll_rewards_program, escalate_compliance_issue, escalate_fraud_case,
    execute_forex_conversion, execute_money_market_deal, extend_loan_tenure,
    fatca_screening, fetch_aa_data, fetch_ckyc_record,
    fetch_existing_loan_details, file_drt_case, file_ecb_return,
    file_gst_return, file_insurance_claim, flag_adverse_media,
    flag_document_discrepancy, flag_group_default, flag_transaction,
    foreclose_loan, freeze_account, generate_account_number,
    generate_account_statement, generate_alm_report, generate_atm_report,
    generate_audit_certificate, generate_audit_trail_report,
    generate_balance_certificate, generate_balance_sheet, generate_basel_report,
    generate_cam_report, generate_campaign_report, generate_card_statement,
    generate_challan, generate_cibil_report, generate_cma_report,
    generate_collection_letter, generate_collection_schedule,
    generate_collections_report, generate_crar_report,
    generate_credit_information_report, generate_credit_rating_migration,
    generate_crr_report, generate_customer_consent, generate_customer_id,
    generate_day_book, generate_disclosure_report, generate_duplicate_statement,
    generate_e_nach_mandate, generate_e_stamp, generate_early_warning_signal,
    generate_encashment_certificate, generate_exposure_report,
    generate_financial_report, generate_form_16a, generate_form_26as_data,
    generate_form_a2, generate_ifrs_report, generate_itr_acknowledgement,
    generate_kyc_audit_trail, generate_kyc_deficiency_notice,
    generate_kyc_report, generate_large_exposure_report,
    generate_liquidity_report, generate_loan_account_number,
    generate_loan_kyc_report, generate_loan_recall_notice,
    generate_merchant_mdr_report, generate_merchant_statement,
    generate_mis_report, generate_otp, generate_payment_advice,
    generate_payment_receipt, generate_priority_sector_report,
    generate_profit_loss_report, generate_provisional_certificate,
    generate_provisional_statement, generate_rbi_return, generate_report,
    generate_risk_report, generate_sanction_advice, generate_sar,
    generate_slr_report, generate_soa, generate_stock_audit_report,
    generate_swift_message, generate_tds_return, generate_utr_number,
    generate_virtual_account, get_account_balance, get_transaction,
    initiate_account_portability, initiate_auction, initiate_fraud_investigation,
    initiate_lok_adalat, initiate_sarfaesi, initiate_sarfaesi_notice,
    initiate_telecall, initiate_telecalling_campaign, initiate_video_kyc,
    initiate_wire_transfer, invest_in_mutual_fund, investigate_fraud_case,
    invoke_bank_guarantee, issue_bank_certificate, issue_bank_guarantee,
    issue_cheque_book, issue_credit_card, issue_debit_card,
    issue_demand_draft_cancellation, issue_letter_of_credit,
    issue_no_due_certificate, issue_tds_certificate, issue_travel_card,
    issue_virtual_card, kyc_periodic_review, link_aadhaar, link_pan,
    log_collection_remarks, log_daily_activity, manage_investment_portfolio,
    manage_nostro_account, manage_vostro_account, mark_account_unclaimed,
    mark_as_irrecoverable, mark_emi_bounce, mark_wilful_defaulter,
    merge_duplicate_customers, monitor_end_use, negotiate_lc_documents,
    negotiate_payment_plan, notify_branch, notify_customer,
    notify_developer_disbursement, notify_manager, notify_payment_failure,
    offboard_customer, onboard_customer, onboard_merchant, open_current_account,
    open_fcnr_deposit, open_nre_account, open_nro_account, open_savings_account,
    open_staff_account, part_prepay_loan, partial_disbursement,
    pause_scheduled_job, pay_credit_card_bill, pay_utility_bill,
    perform_cash_verification, perform_concurrent_audit,
    perform_customer_due_diligence, perform_enhanced_due_diligence,
    perform_eod_processing, perform_fatca_reporting, perform_fraud_rule_update,
    perform_month_end_processing, perform_name_screening, perform_sox_compliance,
    perform_stress_testing, perform_transaction_monitoring,
    perform_transaction_screening, perform_video_kyc, pre_approve_loan,
    pre_disbursement_check, premature_close_fd, process_ach_debit,
    process_address_change, process_adhoc_limit, process_advance_tax,
    process_aeps_transaction, process_atal_pension, process_atm_deposit,
    process_atm_withdrawal, process_bancassurance_referral, process_bbps_payment,
    process_bill_collection, process_bill_discounting,
    process_broken_period_interest, process_bulk_payment, process_cash_deposit,
    process_cash_withdrawal, process_cd_issuance, process_cheque_deposit,
    process_co_lending, process_collect_request, process_consortium_lending,
    process_court_attachment, process_cp_investment, process_credit_insurance,
    process_crop_insurance, process_currency_option, process_dbt_credit,
    process_dd_request, process_digital_lending, process_dividend_payment,
    process_ecb_drawdown, process_education_loan, process_email_update,
    process_emi_payment, process_encashment, process_escrow_account,
    process_export_bill, process_fd_maturity, process_flexi_deposit,
    process_forex_transaction, process_forward_contract, process_gold_loan,
    process_government_securities, process_govt_payment, process_group_insurance,
    process_guarantee_commission, process_ibpc_transaction, process_import_bill,
    process_income_tax_attachment, process_interest_payment,
    process_interest_rate_reset, process_interest_rate_swap,
    process_inward_clearing, process_inward_remittance, process_jan_dhan_account,
    process_kisan_credit_card, process_lc_commission, process_lead_bank_report,
    process_letter_of_comfort, process_limit_renewal, process_loan_transfer,
    process_merchant_settlement, process_minor_to_major_conversion,
    process_mobile_number_update, process_moratorium, process_msme_loan,
    process_mudra_loan, process_nach_return, process_name_change,
    process_neft_inward, process_nostro_reconciliation, process_nri_repatriation,
    process_outward_clearing, process_outward_remittance,
    process_overdraft_review, process_passbook_printing, process_pay_order,
    process_penny_drop, process_pension_payment, process_pmay_subsidy,
    process_pmegp_loan, process_pos_chargeback, process_positive_pay,
    process_prepaid_card_load, process_priority_sector_certificate,
    process_project_finance_drawdown, process_qr_payment, process_rd_installment,
    process_repo_transaction, process_rtc_reporting, process_rtgs_inward,
    process_salary_upload, process_senior_citizen_fd, process_settlement_offer,
    process_settlement_payment, process_standing_instruction,
    process_subsidy_claim, process_subsidy_credit, process_succession_claim,
    process_sukanya_samriddhi, process_sweep_instruction, process_swift_transfer,
    process_tax_saving_fd, process_tc_issuance, process_tds_exemption,
    process_tds_refund_claim, process_technical_write_off, process_token_issuance,
    process_upi_dispute, process_upi_payment, process_vendor_payment,
    process_whistle_blower_report, process_will_execution,
    process_will_registration, process_working_capital_assessment,
    put_loan_on_hold, rate_reset_notification, reactivate_customer,
    recalculate_emi, receive_loan_application, reconcile_atm_transactions,
    reconcile_inter_branch, reconcile_transaction, reconcile_upi_transactions,
    record_center_attendance, record_field_visit, record_telecalling_outcome,
    redeem_reward_points, reduce_loan_tenure, refer_to_credit_committee,
    refund_transaction, register_e_mandate, register_mobile_banking,
    register_nach_mandate, register_netbanking, register_udyam,
    register_upi_handle, register_upi_mandate, reject_document,
    reject_group_application, reject_kyc, release_bank_guarantee,
    release_collateral, release_collateral_charge, release_loan_hold,
    reload_travel_card, remove_joint_holder, renew_fixed_deposit,
    renew_insurance_policy, replace_card, replenish_atm_cash,
    report_cyber_incident, report_fraud_incident, report_fraud_to_rbi,
    request_additional_document, request_additional_information,
    request_missing_documents, reset_banking_password, reset_card_pin,
    reset_netbanking_password, resolve_card_dispute, resume_scheduled_job,
    retrieve_document, retry_task, return_cheque, return_inward_payment,
    reverse_atm_failed_transaction, review_credit_limit, run_dedupe_check,
    run_portfolio_analysis, schedule_bulk_call, schedule_bulk_message,
    schedule_center_meeting, schedule_daily_call, schedule_daily_message,
    schedule_email_campaign, schedule_field_verification, schedule_field_visit,
    schedule_follow_up, schedule_ivr_call, schedule_personal_discussion,
    schedule_sms_campaign, schedule_telecalling_shift,
    schedule_whatsapp_message, score_application, send_audit_report,
    send_balance_transfer_request, send_bounce_notification,
    send_cibil_low_alert, send_covenant_breach_alert,
    send_customer_communication, send_demand_notice, send_disbursement_advice,
    send_document_checklist, send_document_for_signing, send_dpd_alert,
    send_email, send_email_notification, send_foreclosure_statement,
    send_fraud_alert, send_insurance_reminder, send_invoice, send_kyc_reminder,
    send_legal_notice, send_loan_offer, send_login_fee_receipt, send_noc,
    send_notification, send_overdue_notice, send_passbook_update,
    send_payment_confirmation, send_payment_reminder, send_possession_notice,
    send_push_notification, send_rc_endorsement_notice, send_rejection_letter,
    send_reminder, send_repayment_sms, send_risk_alert, send_sanction_terms,
    send_settlement_offer, send_sms, send_sms_notification, send_statement,
    send_technical_report, send_validation_documents,
    send_vehicle_delivery_confirmation, send_welcome_kit,
    send_whatsapp_notification, set_card_limit, set_repayment_mode,
    set_transaction_limit, settle_clearing_batch, settle_forex_deal,
    settle_transaction, stamp_duty_payment, start_sip,
    start_transaction_investigation, start_workflow, stop_cheque, stop_sip,
    str_reporting, surrender_locker, suspend_customer, take_possession,
    top_up_loan, track_field_visit, transfer_account_branch, transfer_funds,
    transfer_to_deaf, transfer_to_securitization, trigger_webhook,
    trigger_workflow_at_time, unblock_card, unfreeze_account,
    update_account_mandate, update_account_status, update_collateral_value,
    update_collection_status, update_customer_profile, update_dpd_bucket,
    update_fatca_declaration, update_kyc_details, update_nominee,
    update_payment_method, upgrade_account_rating, upgrade_borrower_cycle,
    upgrade_credit_card, upgrade_npa_to_standard, upload_ckyc_record,
    validate_account_number, validate_data_quality, validate_ifsc, validate_tin,
    verify_aadhaar, verify_address, verify_beneficial_ownership,
    verify_beneficiary, verify_cersai_registration, verify_collateral,
    verify_company_registration, verify_customer, verify_customer_documents,
    verify_digital_signature, verify_document, verify_driving_license,
    verify_employment, verify_esign, verify_group_members,
    verify_gst_registration, verify_guarantor, verify_nach_status, verify_otp,
    verify_pan, verify_passport, verify_property_title, verify_residence,
    verify_upi_registration, verify_voter_id, withdraw_loan_application,
)


# ── Production handler map ────────────────────────────────────────────────────

_PRODUCTION_HANDLER_MAP: dict = {

    # Internal state & lifecycle
    "update_entity_status":       update_entity_status,
    "flag_for_review":            flag_for_review,
    "lock_account":               lock_account,
    "unlock_account":             unlock_account,
    "close_case":                 close_case,
    "escalate_case":              escalate_case,
    "assign_senior_officer":      assign_senior_officer,
    "escalate_to_rm":             escalate_to_rm,
    "create_audit_record":        create_audit_record,
    "fail_randomly":              fail_randomly,

    # Loan decisioning
    "validate_payment":           validate_payment_handler,
    "assess_creditworthiness":    assess_creditworthiness,
    "approve_loan":               approve_loan,
    "reject_loan":                reject_loan,
    "reject_loan_application":    reject_loan_application,
    "approve_underwriting":       approve_underwriting,
    "reject_underwriting":        reject_underwriting,
    "calculate_emi":              calculate_emi,
    "calculate_risk_score":       calculate_risk_score,
    "flag_high_risk_customer":    flag_high_risk_customer,

    # Loan financial operations
    "disburse_loan":              disburse_loan,
    "generate_loan_agreement":    generate_loan_agreement,
    "apply_credit":               apply_credit,
    "calculate_tax":              calculate_tax,
    "create_payment":             create_payment,
    "validate_transaction":       validate_transaction,
    "verify_compliance":          verify_compliance,

    # Collections & recovery
    "initiate_collection":        initiate_collection,
    "assign_recovery_agent":      assign_recovery_agent,
    "initiate_legal_action":      initiate_legal_action,
    "write_off_loan":             write_off_loan,
    "restructure_loan":           restructure_loan,
    "waive_penalty":              waive_penalty,

    # Account management
    "open_account":               open_account,
    "close_account":              close_account,
    "upgrade_account":            upgrade_account,
    "block_debit_card":           block_debit_card,
    "issue_new_card":             issue_new_card,
    "update_credit_limit":        update_credit_limit,
    "activate_overdraft":         activate_overdraft,
    "reactivate_dormant_account": reactivate_dormant_account,

    # Funds & transaction management
    "hold_funds":                 hold_funds,
    "release_funds":              release_funds,
    "freeze_suspicious_account":  freeze_suspicious_account,
    "reverse_transaction":        reverse_transaction,
    "charge_penalty":             charge_penalty,
    "apply_interest":             apply_interest,
    "process_neft":               process_neft,
    "process_rtgs":               process_rtgs,
    "process_imps":               process_imps,

    # Compliance & risk screening
    "aml_screening":              aml_screening,
    "sanctions_check":            sanctions_check,
    "submit_regulatory_report":   submit_regulatory_report,
    "run_bureau_check":           run_bureau_check,
    "process_credit_check":       process_credit_check,
    "reconcile_account":          reconcile_account,
    "approve_invoice":            approve_invoice,

    # KYC lifecycle
    "initiate_kyc":               initiate_kyc,
    "complete_kyc":               complete_kyc,
    "collect_documents":          collect_documents,

    # Scheduling & internal assignment
    "schedule_customer_callback": schedule_customer_callback,

    # Document generation (persisted via file storage layer)
    "generate_pdf":               generate_pdf,
    "generate_csv":               generate_csv,
    "generate_excel":             generate_excel,

    # Support — internal operations
    "create_support_ticket":      create_support_ticket,
    "assign_support_agent":       assign_support_agent,
    "escalate_to_tier2":          escalate_to_tier2,
    "flag_repeat_complaint":      flag_repeat_complaint,
    "resolve_ticket":             resolve_ticket,
    "process_refund":             process_refund,
    "close_ticket_no_response":   close_ticket_no_response,

    # Health — internal clinical operations
    "schedule_appointment":       schedule_appointment,
    "alert_care_team":            alert_care_team,
    "escalate_to_specialist":     escalate_to_specialist,
    "trigger_emergency_protocol": trigger_emergency_protocol,
    "flag_high_risk_patient":     flag_high_risk_patient,
    "request_insurance_approval": request_insurance_approval,

    # Loan processing — internal verification
    "run_cibil_check":                     run_cibil_check,
    "run_income_verification":             run_income_verification,
    "verify_submitted_documents":          verify_submitted_documents,
    "issue_sanction_letter":               issue_sanction_letter,
    "generate_repayment_schedule":         generate_repayment_schedule,
    "link_insurance_to_loan":              link_insurance_to_loan,
    "collect_post_disbursement_documents": collect_post_disbursement_documents,
    "generate_interest_certificate":       generate_interest_certificate,
    "update_cibil_post_closure":           update_cibil_post_closure,

    # Home loan — physical verification
    "initiate_property_valuation":         initiate_property_valuation,
    "schedule_technical_visit":            schedule_technical_visit,
    "initiate_legal_verification":         initiate_legal_verification,
    "send_to_legal_team":                  send_to_legal_team,
    "raise_legal_query":                   raise_legal_query,
    "legal_verification_cleared":          legal_verification_cleared,
    "register_mortgage":                   register_mortgage,
    "collect_original_property_documents": collect_original_property_documents,
    "disburse_tranche":                    disburse_tranche,
    "return_original_documents":           return_original_documents,

    # Car loan — vehicle verification
    "initiate_vehicle_valuation":  initiate_vehicle_valuation,
    "verify_dealer_invoice":       verify_dealer_invoice,
    "coordinate_with_dealer":      coordinate_with_dealer,
    "disburse_to_dealer":          disburse_to_dealer,
    "initiate_rc_hypothecation":   initiate_rc_hypothecation,
    "verify_vehicle_insurance":    verify_vehicle_insurance,
    "release_hypothecation":       release_hypothecation,

    # ── Catalog stubs — all remaining ActionDefinition entries ────────────────
    # Simulate realistic latency + ~8% failure rate so retry/DLQ/trace logic
    # can be exercised end-to-end without real integrations.
    "abort_workflow":                          abort_workflow,
    "activate_account_aggregator":             activate_account_aggregator,
    "activate_card":                           activate_card,
    "activate_pos_terminal":                   activate_pos_terminal,
    "activate_sms_alerts":                     activate_sms_alerts,
    "add_beneficiary":                         add_beneficiary,
    "add_joint_holder":                        add_joint_holder,
    "add_nominee":                             add_nominee,
    "advise_letter_of_credit":                 advise_letter_of_credit,
    "allot_safe_deposit_locker":               allot_safe_deposit_locker,
    "amend_letter_of_credit":                  amend_letter_of_credit,
    "apply_bounce_charges":                    apply_bounce_charges,
    "apply_credit_card":                       apply_credit_card,
    "apply_subvention":                        apply_subvention,
    "appraise_gold":                           appraise_gold,
    "approve_one_time_settlement":             approve_one_time_settlement,
    "approve_restructuring":                   approve_restructuring,
    "approve_top_up_loan":                     approve_top_up_loan,
    "archive_document":                        archive_document,
    "assign_collection_agent":                 assign_collection_agent,
    "assign_collection_bucket":                assign_collection_bucket,
    "assign_credit_officer":                   assign_credit_officer,
    "assign_customer_segment":                 assign_customer_segment,
    "assign_field_officer":                    assign_field_officer,
    "assign_legal_counsel":                    assign_legal_counsel,
    "assign_relationship_manager":             assign_relationship_manager,
    "assign_telecalling_agents":               assign_telecalling_agents,
    "auction_collateral":                      auction_collateral,
    "block_credit_card":                       block_credit_card,
    "block_fraudulent_transaction":            block_fraudulent_transaction,
    "block_upi_id":                            block_upi_id,
    "book_forex_deal":                         book_forex_deal,
    "calculate_account_balance":               calculate_account_balance,
    "calculate_alm_gap":                       calculate_alm_gap,
    "calculate_credit_score":                  calculate_credit_score,
    "calculate_debt_service_ratio":            calculate_debt_service_ratio,
    "calculate_eblr":                          calculate_eblr,
    "calculate_eligibility":                   calculate_eligibility,
    "calculate_fd_interest":                   calculate_fd_interest,
    "calculate_foreclosure_amount":            calculate_foreclosure_amount,
    "calculate_forex_margin":                  calculate_forex_margin,
    "calculate_group_utilization":             calculate_group_utilization,
    "calculate_hedge_effectiveness":           calculate_hedge_effectiveness,
    "calculate_interest":                      calculate_interest,
    "calculate_interest_rate":                 calculate_interest_rate,
    "calculate_loan_eligibility":              calculate_loan_eligibility,
    "calculate_ltv_ratio":                     calculate_ltv_ratio,
    "calculate_mark_to_market":                calculate_mark_to_market,
    "calculate_mclr":                          calculate_mclr,
    "calculate_penal_interest":                calculate_penal_interest,
    "calculate_penalty_on_premature_withdrawal": calculate_penalty_on_premature_withdrawal,
    "calculate_prepayment_charges":            calculate_prepayment_charges,
    "calculate_provision_coverage":            calculate_provision_coverage,
    "calculate_rd_maturity":                   calculate_rd_maturity,
    "cancel_nach_mandate":                     cancel_nach_mandate,
    "cancel_scheduled_job":                    cancel_scheduled_job,
    "cancel_standing_instruction":             cancel_standing_instruction,
    "capture_biometric":                       capture_biometric,
    "capture_customer_photograph":             capture_customer_photograph,
    "change_emi_date":                         change_emi_date,
    "charge_locker_rent":                      charge_locker_rent,
    "check_fema_compliance":                   check_fema_compliance,
    "check_pep_status":                        check_pep_status,
    "classify_asset_quality":                  classify_asset_quality,
    "classify_customer_risk":                  classify_customer_risk,
    "classify_npa":                            classify_npa,
    "close_credit_card":                       close_credit_card,
    "close_deposit":                           close_deposit,
    "close_fraud_case":                        close_fraud_case,
    "close_transaction_investigation":         close_transaction_investigation,
    "collect_address_details":                 collect_address_details,
    "collect_address_proof":                   collect_address_proof,
    "collect_asset_liability_details":         collect_asset_liability_details,
    "collect_bank_account_details":            collect_bank_account_details,
    "collect_bank_statement":                  collect_bank_statement,
    "collect_biometrics":                      collect_biometrics,
    "collect_business_details":                collect_business_details,
    "collect_business_proof":                  collect_business_proof,
    "collect_contact_details":                 collect_contact_details,
    "collect_dependents_details":              collect_dependents_details,
    "collect_digital_consent":                 collect_digital_consent,
    "collect_document_requirements":           collect_document_requirements,
    "collect_education_details":               collect_education_details,
    "collect_employment_certificate":          collect_employment_certificate,
    "collect_employment_details":              collect_employment_details,
    "collect_existing_loan_details":           collect_existing_loan_details,
    "collect_family_details":                  collect_family_details,
    "collect_field_photographs":               collect_field_photographs,
    "collect_field_verification":              collect_field_verification,
    "collect_geotag_data":                     collect_geotag_data,
    "collect_group_repayment":                 collect_group_repayment,
    "collect_guarantor_details":               collect_guarantor_details,
    "collect_identity_proof":                  collect_identity_proof,
    "collect_income_details":                  collect_income_details,
    "collect_income_proof":                    collect_income_proof,
    "collect_insurance_certificate":           collect_insurance_certificate,
    "collect_insurance_documents":             collect_insurance_documents,
    "collect_itr_documents":                   collect_itr_documents,
    "collect_legal_documents":                 collect_legal_documents,
    "collect_marital_status":                  collect_marital_status,
    "collect_medical_history":                 collect_medical_history,
    "collect_mortgage_documents":              collect_mortgage_documents,
    "collect_next_of_kin_details":             collect_next_of_kin_details,
    "collect_nominee_details":                 collect_nominee_details,
    "collect_occupation_details":              collect_occupation_details,
    "collect_personal_details":                collect_personal_details,
    "collect_photo":                           collect_photo,
    "collect_property_details":                collect_property_details,
    "collect_property_documents":              collect_property_documents,
    "collect_reference_details":               collect_reference_details,
    "collect_sanction_letter_copy":            collect_sanction_letter_copy,
    "collect_selfie_verification":             collect_selfie_verification,
    "collect_signature":                       collect_signature,
    "collect_signed_agreement":                collect_signed_agreement,
    "collect_tcs_on_remittance":               collect_tcs_on_remittance,
    "collect_technical_documents":             collect_technical_documents,
    "collect_vehicle_details":                 collect_vehicle_details,
    "collect_vehicle_documents":               collect_vehicle_documents,
    "collect_voice_biometric":                 collect_voice_biometric,
    "collect_witness_details":                 collect_witness_details,
    "compute_cost_of_funds":                   compute_cost_of_funds,
    "compute_depreciation":                    compute_depreciation,
    "compute_drawing_power":                   compute_drawing_power,
    "compute_ecl":                             compute_ecl,
    "compute_gst":                             compute_gst,
    "compute_interest_on_interest":            compute_interest_on_interest,
    "compute_internal_rating":                 compute_internal_rating,
    "compute_nii":                             compute_nii,
    "compute_provisioning":                    compute_provisioning,
    "compute_recovery_progress":               compute_recovery_progress,
    "conditional_approve_loan":                conditional_approve_loan,
    "conduct_cgt":                             conduct_cgt,
    "conduct_grt":                             conduct_grt,
    "conduct_personal_discussion":             conduct_personal_discussion,
    "conduct_stock_audit":                     conduct_stock_audit,
    "confirm_letter_of_credit":                confirm_letter_of_credit,
    "convert_to_card_emi":                     convert_to_card_emi,
    "create_audit_event":                      create_audit_event,
    "create_collateral_charge":                create_collateral_charge,
    "create_customer":                         create_customer,
    "create_customer_profile":                 create_customer_profile,
    "create_fixed_deposit":                    create_fixed_deposit,
    "create_group_loan":                       create_group_loan,
    "create_loan_application":                 create_loan_application,
    "create_mortgage_deed":                    create_mortgage_deed,
    "create_notification_task":                create_notification_task,
    "create_recurring_deposit":                create_recurring_deposit,
    "create_standing_instruction":             create_standing_instruction,
    "credit_interest_to_account":              credit_interest_to_account,
    "ctr_reporting":                           ctr_reporting,
    "deactivate_customer":                     deactivate_customer,
    "deactivate_overdraft":                    deactivate_overdraft,
    "deactivate_sms_alerts":                   deactivate_sms_alerts,
    "deactivate_upi_mandate":                  deactivate_upi_mandate,
    "deduct_tds":                              deduct_tds,
    "disable_international_usage":             disable_international_usage,
    "dispute_card_transaction":                dispute_card_transaction,
    "dissolve_group":                          dissolve_group,
    "downgrade_account":                       downgrade_account,
    "downgrade_account_rating":                downgrade_account_rating,
    "drill_locker":                            drill_locker,
    "enable_international_usage":              enable_international_usage,
    "enable_internet_banking":                 enable_internet_banking,
    "enable_mobile_banking":                   enable_mobile_banking,
    "enable_upi":                              enable_upi,
    "enable_upi_autopay":                      enable_upi_autopay,
    "enroll_health_insurance":                 enroll_health_insurance,
    "enroll_life_insurance":                   enroll_life_insurance,
    "enroll_rewards_program":                  enroll_rewards_program,
    "escalate_compliance_issue":               escalate_compliance_issue,
    "escalate_fraud_case":                     escalate_fraud_case,
    "execute_forex_conversion":                execute_forex_conversion,
    "execute_money_market_deal":               execute_money_market_deal,
    "extend_loan_tenure":                      extend_loan_tenure,
    "fatca_screening":                         fatca_screening,
    "fetch_aa_data":                           fetch_aa_data,
    "fetch_ckyc_record":                       fetch_ckyc_record,
    "fetch_existing_loan_details":             fetch_existing_loan_details,
    "file_drt_case":                           file_drt_case,
    "file_ecb_return":                         file_ecb_return,
    "file_gst_return":                         file_gst_return,
    "file_insurance_claim":                    file_insurance_claim,
    "flag_adverse_media":                      flag_adverse_media,
    "flag_document_discrepancy":               flag_document_discrepancy,
    "flag_group_default":                      flag_group_default,
    "flag_transaction":                        flag_transaction,
    "foreclose_loan":                          foreclose_loan,
    "freeze_account":                          freeze_account,
    "generate_account_number":                 generate_account_number,
    "generate_account_statement":              generate_account_statement,
    "generate_alm_report":                     generate_alm_report,
    "generate_atm_report":                     generate_atm_report,
    "generate_audit_certificate":              generate_audit_certificate,
    "generate_audit_trail_report":             generate_audit_trail_report,
    "generate_balance_certificate":            generate_balance_certificate,
    "generate_balance_sheet":                  generate_balance_sheet,
    "generate_basel_report":                   generate_basel_report,
    "generate_cam_report":                     generate_cam_report,
    "generate_campaign_report":                generate_campaign_report,
    "generate_card_statement":                 generate_card_statement,
    "generate_challan":                        generate_challan,
    "generate_cibil_report":                   generate_cibil_report,
    "generate_cma_report":                     generate_cma_report,
    "generate_collection_letter":              generate_collection_letter,
    "generate_collection_schedule":            generate_collection_schedule,
    "generate_collections_report":             generate_collections_report,
    "generate_crar_report":                    generate_crar_report,
    "generate_credit_information_report":      generate_credit_information_report,
    "generate_credit_rating_migration":        generate_credit_rating_migration,
    "generate_crr_report":                     generate_crr_report,
    "generate_customer_consent":               generate_customer_consent,
    "generate_customer_id":                    generate_customer_id,
    "generate_day_book":                       generate_day_book,
    "generate_disclosure_report":              generate_disclosure_report,
    "generate_duplicate_statement":            generate_duplicate_statement,
    "generate_e_nach_mandate":                 generate_e_nach_mandate,
    "generate_e_stamp":                        generate_e_stamp,
    "generate_early_warning_signal":           generate_early_warning_signal,
    "generate_encashment_certificate":         generate_encashment_certificate,
    "generate_exposure_report":                generate_exposure_report,
    "generate_financial_report":               generate_financial_report,
    "generate_form_16a":                       generate_form_16a,
    "generate_form_26as_data":                 generate_form_26as_data,
    "generate_form_a2":                        generate_form_a2,
    "generate_ifrs_report":                    generate_ifrs_report,
    "generate_itr_acknowledgement":            generate_itr_acknowledgement,
    "generate_kyc_audit_trail":                generate_kyc_audit_trail,
    "generate_kyc_deficiency_notice":          generate_kyc_deficiency_notice,
    "generate_kyc_report":                     generate_kyc_report,
    "generate_large_exposure_report":          generate_large_exposure_report,
    "generate_liquidity_report":               generate_liquidity_report,
    "generate_loan_account_number":            generate_loan_account_number,
    "generate_loan_kyc_report":                generate_loan_kyc_report,
    "generate_loan_recall_notice":             generate_loan_recall_notice,
    "generate_merchant_mdr_report":            generate_merchant_mdr_report,
    "generate_merchant_statement":             generate_merchant_statement,
    "generate_mis_report":                     generate_mis_report,
    "generate_otp":                            generate_otp,
    "generate_payment_advice":                 generate_payment_advice,
    "generate_payment_receipt":                generate_payment_receipt,
    "generate_priority_sector_report":         generate_priority_sector_report,
    "generate_profit_loss_report":             generate_profit_loss_report,
    "generate_provisional_certificate":        generate_provisional_certificate,
    "generate_provisional_statement":          generate_provisional_statement,
    "generate_rbi_return":                     generate_rbi_return,
    "generate_report":                         generate_report,
    "generate_risk_report":                    generate_risk_report,
    "generate_sanction_advice":                generate_sanction_advice,
    "generate_sar":                            generate_sar,
    "generate_slr_report":                     generate_slr_report,
    "generate_soa":                            generate_soa,
    "generate_stock_audit_report":             generate_stock_audit_report,
    "generate_swift_message":                  generate_swift_message,
    "generate_tds_return":                     generate_tds_return,
    "generate_utr_number":                     generate_utr_number,
    "generate_virtual_account":                generate_virtual_account,
    "get_account_balance":                     get_account_balance,
    "get_transaction":                         get_transaction,
    "initiate_account_portability":            initiate_account_portability,
    "initiate_auction":                        initiate_auction,
    "initiate_fraud_investigation":            initiate_fraud_investigation,
    "initiate_lok_adalat":                     initiate_lok_adalat,
    "initiate_sarfaesi":                       initiate_sarfaesi,
    "initiate_sarfaesi_notice":                initiate_sarfaesi_notice,
    "initiate_telecall":                       initiate_telecall,
    "initiate_telecalling_campaign":           initiate_telecalling_campaign,
    "initiate_video_kyc":                      initiate_video_kyc,
    "initiate_wire_transfer":                  initiate_wire_transfer,
    "invest_in_mutual_fund":                   invest_in_mutual_fund,
    "investigate_fraud_case":                  investigate_fraud_case,
    "invoke_bank_guarantee":                   invoke_bank_guarantee,
    "issue_bank_certificate":                  issue_bank_certificate,
    "issue_bank_guarantee":                    issue_bank_guarantee,
    "issue_cheque_book":                       issue_cheque_book,
    "issue_credit_card":                       issue_credit_card,
    "issue_debit_card":                        issue_debit_card,
    "issue_demand_draft_cancellation":         issue_demand_draft_cancellation,
    "issue_letter_of_credit":                  issue_letter_of_credit,
    "issue_no_due_certificate":                issue_no_due_certificate,
    "issue_tds_certificate":                   issue_tds_certificate,
    "issue_travel_card":                       issue_travel_card,
    "issue_virtual_card":                      issue_virtual_card,
    "kyc_periodic_review":                     kyc_periodic_review,
    "link_aadhaar":                            link_aadhaar,
    "link_pan":                                link_pan,
    "log_collection_remarks":                  log_collection_remarks,
    "log_daily_activity":                      log_daily_activity,
    "manage_investment_portfolio":             manage_investment_portfolio,
    "manage_nostro_account":                   manage_nostro_account,
    "manage_vostro_account":                   manage_vostro_account,
    "mark_account_unclaimed":                  mark_account_unclaimed,
    "mark_as_irrecoverable":                   mark_as_irrecoverable,
    "mark_emi_bounce":                         mark_emi_bounce,
    "mark_wilful_defaulter":                   mark_wilful_defaulter,
    "merge_duplicate_customers":               merge_duplicate_customers,
    "monitor_end_use":                         monitor_end_use,
    "negotiate_lc_documents":                  negotiate_lc_documents,
    "negotiate_payment_plan":                  negotiate_payment_plan,
    "notify_branch":                           notify_branch,
    "notify_customer":                         notify_customer,
    "notify_developer_disbursement":           notify_developer_disbursement,
    "notify_manager":                          notify_manager,
    "notify_payment_failure":                  notify_payment_failure,
    "offboard_customer":                       offboard_customer,
    "onboard_customer":                        onboard_customer,
    "onboard_merchant":                        onboard_merchant,
    "open_current_account":                    open_current_account,
    "open_fcnr_deposit":                       open_fcnr_deposit,
    "open_nre_account":                        open_nre_account,
    "open_nro_account":                        open_nro_account,
    "open_savings_account":                    open_savings_account,
    "open_staff_account":                      open_staff_account,
    "part_prepay_loan":                        part_prepay_loan,
    "partial_disbursement":                    partial_disbursement,
    "pause_scheduled_job":                     pause_scheduled_job,
    "pay_credit_card_bill":                    pay_credit_card_bill,
    "pay_utility_bill":                        pay_utility_bill,
    "perform_cash_verification":               perform_cash_verification,
    "perform_concurrent_audit":                perform_concurrent_audit,
    "perform_customer_due_diligence":          perform_customer_due_diligence,
    "perform_enhanced_due_diligence":          perform_enhanced_due_diligence,
    "perform_eod_processing":                  perform_eod_processing,
    "perform_fatca_reporting":                 perform_fatca_reporting,
    "perform_fraud_rule_update":               perform_fraud_rule_update,
    "perform_month_end_processing":            perform_month_end_processing,
    "perform_name_screening":                  perform_name_screening,
    "perform_sox_compliance":                  perform_sox_compliance,
    "perform_stress_testing":                  perform_stress_testing,
    "perform_transaction_monitoring":          perform_transaction_monitoring,
    "perform_transaction_screening":           perform_transaction_screening,
    "perform_video_kyc":                       perform_video_kyc,
    "pre_approve_loan":                        pre_approve_loan,
    "pre_disbursement_check":                  pre_disbursement_check,
    "premature_close_fd":                      premature_close_fd,
    "process_ach_debit":                       process_ach_debit,
    "process_address_change":                  process_address_change,
    "process_adhoc_limit":                     process_adhoc_limit,
    "process_advance_tax":                     process_advance_tax,
    "process_aeps_transaction":                process_aeps_transaction,
    "process_atal_pension":                    process_atal_pension,
    "process_atm_deposit":                     process_atm_deposit,
    "process_atm_withdrawal":                  process_atm_withdrawal,
    "process_bancassurance_referral":          process_bancassurance_referral,
    "process_bbps_payment":                    process_bbps_payment,
    "process_bill_collection":                 process_bill_collection,
    "process_bill_discounting":                process_bill_discounting,
    "process_broken_period_interest":          process_broken_period_interest,
    "process_bulk_payment":                    process_bulk_payment,
    "process_cash_deposit":                    process_cash_deposit,
    "process_cash_withdrawal":                 process_cash_withdrawal,
    "process_cd_issuance":                     process_cd_issuance,
    "process_cheque_deposit":                  process_cheque_deposit,
    "process_co_lending":                      process_co_lending,
    "process_collect_request":                 process_collect_request,
    "process_consortium_lending":              process_consortium_lending,
    "process_court_attachment":                process_court_attachment,
    "process_cp_investment":                   process_cp_investment,
    "process_credit_insurance":                process_credit_insurance,
    "process_crop_insurance":                  process_crop_insurance,
    "process_currency_option":                 process_currency_option,
    "process_dbt_credit":                      process_dbt_credit,
    "process_dd_request":                      process_dd_request,
    "process_digital_lending":                 process_digital_lending,
    "process_dividend_payment":                process_dividend_payment,
    "process_ecb_drawdown":                    process_ecb_drawdown,
    "process_education_loan":                  process_education_loan,
    "process_email_update":                    process_email_update,
    "process_emi_payment":                     process_emi_payment,
    "process_encashment":                      process_encashment,
    "process_escrow_account":                  process_escrow_account,
    "process_export_bill":                     process_export_bill,
    "process_fd_maturity":                     process_fd_maturity,
    "process_flexi_deposit":                   process_flexi_deposit,
    "process_forex_transaction":               process_forex_transaction,
    "process_forward_contract":                process_forward_contract,
    "process_gold_loan":                       process_gold_loan,
    "process_government_securities":           process_government_securities,
    "process_govt_payment":                    process_govt_payment,
    "process_group_insurance":                 process_group_insurance,
    "process_guarantee_commission":            process_guarantee_commission,
    "process_ibpc_transaction":                process_ibpc_transaction,
    "process_import_bill":                     process_import_bill,
    "process_income_tax_attachment":           process_income_tax_attachment,
    "process_interest_payment":                process_interest_payment,
    "process_interest_rate_reset":             process_interest_rate_reset,
    "process_interest_rate_swap":              process_interest_rate_swap,
    "process_inward_clearing":                 process_inward_clearing,
    "process_inward_remittance":               process_inward_remittance,
    "process_jan_dhan_account":                process_jan_dhan_account,
    "process_kisan_credit_card":               process_kisan_credit_card,
    "process_lc_commission":                   process_lc_commission,
    "process_lead_bank_report":                process_lead_bank_report,
    "process_letter_of_comfort":               process_letter_of_comfort,
    "process_limit_renewal":                   process_limit_renewal,
    "process_loan_transfer":                   process_loan_transfer,
    "process_merchant_settlement":             process_merchant_settlement,
    "process_minor_to_major_conversion":       process_minor_to_major_conversion,
    "process_mobile_number_update":            process_mobile_number_update,
    "process_moratorium":                      process_moratorium,
    "process_msme_loan":                       process_msme_loan,
    "process_mudra_loan":                      process_mudra_loan,
    "process_nach_return":                     process_nach_return,
    "process_name_change":                     process_name_change,
    "process_neft_inward":                     process_neft_inward,
    "process_nostro_reconciliation":           process_nostro_reconciliation,
    "process_nri_repatriation":                process_nri_repatriation,
    "process_outward_clearing":                process_outward_clearing,
    "process_outward_remittance":              process_outward_remittance,
    "process_overdraft_review":                process_overdraft_review,
    "process_passbook_printing":               process_passbook_printing,
    "process_pay_order":                       process_pay_order,
    "process_penny_drop":                      process_penny_drop,
    "process_pension_payment":                 process_pension_payment,
    "process_pmay_subsidy":                    process_pmay_subsidy,
    "process_pmegp_loan":                      process_pmegp_loan,
    "process_pos_chargeback":                  process_pos_chargeback,
    "process_positive_pay":                    process_positive_pay,
    "process_prepaid_card_load":               process_prepaid_card_load,
    "process_priority_sector_certificate":     process_priority_sector_certificate,
    "process_project_finance_drawdown":        process_project_finance_drawdown,
    "process_qr_payment":                      process_qr_payment,
    "process_rd_installment":                  process_rd_installment,
    "process_repo_transaction":                process_repo_transaction,
    "process_rtc_reporting":                   process_rtc_reporting,
    "process_rtgs_inward":                     process_rtgs_inward,
    "process_salary_upload":                   process_salary_upload,
    "process_senior_citizen_fd":               process_senior_citizen_fd,
    "process_settlement_offer":                process_settlement_offer,
    "process_settlement_payment":              process_settlement_payment,
    "process_standing_instruction":            process_standing_instruction,
    "process_subsidy_claim":                   process_subsidy_claim,
    "process_subsidy_credit":                  process_subsidy_credit,
    "process_succession_claim":                process_succession_claim,
    "process_sukanya_samriddhi":               process_sukanya_samriddhi,
    "process_sweep_instruction":               process_sweep_instruction,
    "process_swift_transfer":                  process_swift_transfer,
    "process_tax_saving_fd":                   process_tax_saving_fd,
    "process_tc_issuance":                     process_tc_issuance,
    "process_tds_exemption":                   process_tds_exemption,
    "process_tds_refund_claim":                process_tds_refund_claim,
    "process_technical_write_off":             process_technical_write_off,
    "process_token_issuance":                  process_token_issuance,
    "process_upi_dispute":                     process_upi_dispute,
    "process_upi_payment":                     process_upi_payment,
    "process_vendor_payment":                  process_vendor_payment,
    "process_whistle_blower_report":           process_whistle_blower_report,
    "process_will_execution":                  process_will_execution,
    "process_will_registration":               process_will_registration,
    "process_working_capital_assessment":      process_working_capital_assessment,
    "put_loan_on_hold":                        put_loan_on_hold,
    "rate_reset_notification":                 rate_reset_notification,
    "reactivate_customer":                     reactivate_customer,
    "recalculate_emi":                         recalculate_emi,
    "receive_loan_application":                receive_loan_application,
    "reconcile_atm_transactions":              reconcile_atm_transactions,
    "reconcile_inter_branch":                  reconcile_inter_branch,
    "reconcile_transaction":                   reconcile_transaction,
    "reconcile_upi_transactions":              reconcile_upi_transactions,
    "record_center_attendance":                record_center_attendance,
    "record_field_visit":                      record_field_visit,
    "record_telecalling_outcome":              record_telecalling_outcome,
    "redeem_reward_points":                    redeem_reward_points,
    "reduce_loan_tenure":                      reduce_loan_tenure,
    "refer_to_credit_committee":               refer_to_credit_committee,
    "refund_transaction":                      refund_transaction,
    "register_e_mandate":                      register_e_mandate,
    "register_mobile_banking":                 register_mobile_banking,
    "register_nach_mandate":                   register_nach_mandate,
    "register_netbanking":                     register_netbanking,
    "register_udyam":                          register_udyam,
    "register_upi_handle":                     register_upi_handle,
    "register_upi_mandate":                    register_upi_mandate,
    "reject_document":                         reject_document,
    "reject_group_application":                reject_group_application,
    "reject_kyc":                              reject_kyc,
    "release_bank_guarantee":                  release_bank_guarantee,
    "release_collateral":                      release_collateral,
    "release_collateral_charge":               release_collateral_charge,
    "release_loan_hold":                       release_loan_hold,
    "reload_travel_card":                      reload_travel_card,
    "remove_joint_holder":                     remove_joint_holder,
    "renew_fixed_deposit":                     renew_fixed_deposit,
    "renew_insurance_policy":                  renew_insurance_policy,
    "replace_card":                            replace_card,
    "replenish_atm_cash":                      replenish_atm_cash,
    "report_cyber_incident":                   report_cyber_incident,
    "report_fraud_incident":                   report_fraud_incident,
    "report_fraud_to_rbi":                     report_fraud_to_rbi,
    "request_additional_document":             request_additional_document,
    "request_additional_information":          request_additional_information,
    "request_missing_documents":               request_missing_documents,
    "reset_banking_password":                  reset_banking_password,
    "reset_card_pin":                          reset_card_pin,
    "reset_netbanking_password":               reset_netbanking_password,
    "resolve_card_dispute":                    resolve_card_dispute,
    "resume_scheduled_job":                    resume_scheduled_job,
    "retrieve_document":                       retrieve_document,
    "retry_task":                              retry_task,
    "return_cheque":                           return_cheque,
    "return_inward_payment":                   return_inward_payment,
    "reverse_atm_failed_transaction":          reverse_atm_failed_transaction,
    "review_credit_limit":                     review_credit_limit,
    "run_dedupe_check":                        run_dedupe_check,
    "run_portfolio_analysis":                  run_portfolio_analysis,
    "schedule_bulk_call":                      schedule_bulk_call,
    "schedule_bulk_message":                   schedule_bulk_message,
    "schedule_center_meeting":                 schedule_center_meeting,
    "schedule_daily_call":                     schedule_daily_call,
    "schedule_daily_message":                  schedule_daily_message,
    "schedule_email_campaign":                 schedule_email_campaign,
    "schedule_field_verification":             schedule_field_verification,
    "schedule_field_visit":                    schedule_field_visit,
    "schedule_follow_up":                      schedule_follow_up,
    "schedule_ivr_call":                       schedule_ivr_call,
    "schedule_personal_discussion":            schedule_personal_discussion,
    "schedule_sms_campaign":                   schedule_sms_campaign,
    "schedule_telecalling_shift":              schedule_telecalling_shift,
    "schedule_whatsapp_message":               schedule_whatsapp_message,
    "score_application":                       score_application,
    "send_audit_report":                       send_audit_report,
    "send_balance_transfer_request":           send_balance_transfer_request,
    "send_bounce_notification":                send_bounce_notification,
    "send_cibil_low_alert":                    send_cibil_low_alert,
    "send_covenant_breach_alert":              send_covenant_breach_alert,
    "send_customer_communication":             send_customer_communication,
    "send_demand_notice":                      send_demand_notice,
    "send_disbursement_advice":                send_disbursement_advice,
    "send_document_checklist":                 send_document_checklist,
    "send_document_for_signing":               send_document_for_signing,
    "send_dpd_alert":                          send_dpd_alert,
    "send_email":                              send_email,
    "send_email_notification":                 send_email_notification,
    "send_foreclosure_statement":              send_foreclosure_statement,
    "send_fraud_alert":                        send_fraud_alert,
    "send_insurance_reminder":                 send_insurance_reminder,
    "send_invoice":                            send_invoice,
    "send_kyc_reminder":                       send_kyc_reminder,
    "send_legal_notice":                       send_legal_notice,
    "send_loan_offer":                         send_loan_offer,
    "send_login_fee_receipt":                  send_login_fee_receipt,
    "send_noc":                                send_noc,
    "send_notification":                       send_notification,
    "send_overdue_notice":                     send_overdue_notice,
    "send_passbook_update":                    send_passbook_update,
    "send_payment_confirmation":               send_payment_confirmation,
    "send_payment_reminder":                   send_payment_reminder,
    "send_possession_notice":                  send_possession_notice,
    "send_push_notification":                  send_push_notification,
    "send_rc_endorsement_notice":              send_rc_endorsement_notice,
    "send_rejection_letter":                   send_rejection_letter,
    "send_reminder":                           send_reminder,
    "send_repayment_sms":                      send_repayment_sms,
    "send_risk_alert":                         send_risk_alert,
    "send_sanction_terms":                     send_sanction_terms,
    "send_settlement_offer":                   send_settlement_offer,
    "send_sms":                                send_sms,
    "send_sms_notification":                   send_sms_notification,
    "send_statement":                          send_statement,
    "send_technical_report":                   send_technical_report,
    "send_validation_documents":               send_validation_documents,
    "send_vehicle_delivery_confirmation":      send_vehicle_delivery_confirmation,
    "send_welcome_kit":                        send_welcome_kit,
    "send_whatsapp_notification":              send_whatsapp_notification,
    "set_card_limit":                          set_card_limit,
    "set_repayment_mode":                      set_repayment_mode,
    "set_transaction_limit":                   set_transaction_limit,
    "settle_clearing_batch":                   settle_clearing_batch,
    "settle_forex_deal":                       settle_forex_deal,
    "settle_transaction":                      settle_transaction,
    "stamp_duty_payment":                      stamp_duty_payment,
    "start_sip":                               start_sip,
    "start_transaction_investigation":         start_transaction_investigation,
    "start_workflow":                          start_workflow,
    "stop_cheque":                             stop_cheque,
    "stop_sip":                                stop_sip,
    "str_reporting":                           str_reporting,
    "surrender_locker":                        surrender_locker,
    "suspend_customer":                        suspend_customer,
    "take_possession":                         take_possession,
    "top_up_loan":                             top_up_loan,
    "track_field_visit":                       track_field_visit,
    "transfer_account_branch":                 transfer_account_branch,
    "transfer_funds":                          transfer_funds,
    "transfer_to_deaf":                        transfer_to_deaf,
    "transfer_to_securitization":              transfer_to_securitization,
    "trigger_webhook":                         trigger_webhook,
    "trigger_workflow_at_time":                trigger_workflow_at_time,
    "unblock_card":                            unblock_card,
    "unfreeze_account":                        unfreeze_account,
    "update_account_mandate":                  update_account_mandate,
    "update_account_status":                   update_account_status,
    "update_collateral_value":                 update_collateral_value,
    "update_collection_status":                update_collection_status,
    "update_customer_profile":                 update_customer_profile,
    "update_dpd_bucket":                       update_dpd_bucket,
    "update_fatca_declaration":                update_fatca_declaration,
    "update_kyc_details":                      update_kyc_details,
    "update_nominee":                          update_nominee,
    "update_payment_method":                   update_payment_method,
    "upgrade_account_rating":                  upgrade_account_rating,
    "upgrade_borrower_cycle":                  upgrade_borrower_cycle,
    "upgrade_credit_card":                     upgrade_credit_card,
    "upgrade_npa_to_standard":                 upgrade_npa_to_standard,
    "upload_ckyc_record":                      upload_ckyc_record,
    "validate_account_number":                 validate_account_number,
    "validate_data_quality":                   validate_data_quality,
    "validate_ifsc":                           validate_ifsc,
    "validate_tin":                            validate_tin,
    "verify_aadhaar":                          verify_aadhaar,
    "verify_address":                          verify_address,
    "verify_beneficial_ownership":             verify_beneficial_ownership,
    "verify_beneficiary":                      verify_beneficiary,
    "verify_cersai_registration":              verify_cersai_registration,
    "verify_collateral":                       verify_collateral,
    "verify_company_registration":             verify_company_registration,
    "verify_customer":                         verify_customer,
    "verify_customer_documents":               verify_customer_documents,
    "verify_digital_signature":                verify_digital_signature,
    "verify_document":                         verify_document,
    "verify_driving_license":                  verify_driving_license,
    "verify_employment":                       verify_employment,
    "verify_esign":                            verify_esign,
    "verify_group_members":                    verify_group_members,
    "verify_gst_registration":                 verify_gst_registration,
    "verify_guarantor":                        verify_guarantor,
    "verify_nach_status":                      verify_nach_status,
    "verify_otp":                              verify_otp,
    "verify_pan":                              verify_pan,
    "verify_passport":                         verify_passport,
    "verify_property_title":                   verify_property_title,
    "verify_residence":                        verify_residence,
    "verify_upi_registration":                 verify_upi_registration,
    "verify_voter_id":                         verify_voter_id,
    "withdraw_loan_application":               withdraw_loan_application,
}


# ── Chaos handler map ─────────────────────────────────────────────────────────

def _make_chaos_handler(action_name: str):
    def _chaos(payload: dict, config: dict) -> dict:
        _apply_chaos(action_name, payload, config)
        return _chaos_response(action_name)
    _chaos.__name__ = f"chaos_{action_name}"
    return _chaos


_CHAOS_HANDLER_MAP: dict = {
    name: _make_chaos_handler(name)
    for name in _PRODUCTION_HANDLER_MAP
}
_CHAOS_HANDLER_MAP.update({
    "escalate_case":         chaos_escalate_case,
    "assign_senior_officer": chaos_assign_senior_officer,
    "close_case":            chaos_close_case,
    "reject_loan":           chaos_reject_loan,
    "fail_randomly":         fail_randomly,
})


# ── Public export ─────────────────────────────────────────────────────────────

_CHAOS_ENABLED = os.getenv("CHAOS_MODE", "false").lower() == "true"

ACTION_HANDLER_MAP: dict = (
    _CHAOS_HANDLER_MAP if _CHAOS_ENABLED else _PRODUCTION_HANDLER_MAP
)
